export const buttonStyles = [
  "bg-transparent",
  "text-inherit",
  "rounded-lg",
  "text-inherit",
  "px-2",
  "py-1",
  "hover:text-blue-700",
  "duration-200",
  "focus:outline-none",
  "focus:text-blue-700",
  "focus:outline-none",
  "flex",
  "justify-center",
  "items-center",
  "disabled:opacity-40",
  "disabled:pointer-disabled",
].join(" ");
